version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    networks:
      - arko 
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    image: harbor.registry.local/jenkins1/nginx1:v1
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - arko
    depends_on:
      - mysql

  backend:
    image: harbor.registry.local/jenkins1/nodejs:v1
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - arko
    depends_on:
      - mysql
    environment:
    DB_HOST: mysql
    DB_USER: root
    DB_PASSWORD: root
    DB_NAME: myapp

networks:
  arko:
volumes:
  db_data:
  
