version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
    ports:
      - "3306:3306"
    networks:
      - naya-network
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    image: ${HARBOR_URL}${IMAGE_NAME_FRONTEND}:${IMAGE_TAG}
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - naya-network
    depends_on:
      - mysql

  backend:
    image: ${HARBOR_URL}${IMAGE_NAME_BACKEND}:${IMAGE_TAG}
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - naya-network
    depends_on:
      - mysql

networks:
  naya-network:
volumes:
  db_data:
  
